name: CI-latest

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.1, 8.2, 8.3, 8.4]

    steps:
      - uses: actions/checkout@v3

      - uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php }}

      - name: PHPUnit Tests
        uses: php-actions/phpunit@master
        with:
          version: 9.6
          php_version: ${{ matrix.php }}
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml.dist
          args: --coverage-text